version: '3.3'
services:
  web:
    image: fazakasedina/web-trains
    links:
      - my_db
    ports:
       - '8088:8088'

  my_db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'feim1911'
      MYSQL_TCP_PORT: '3307'
    ports:
      - '3307:3307'
    expose:
      - '3307'
    
    volumes:
      - my-db:/var/lib/mysql
      # - ./database.sql: /docker-entrypoint-initdb.d/database.sql

volumes:
  my-db:

    #docker-compose up